name: Check for artifact and register release

on:
  workflow_run:
    workflows: ["Maven Release"]
    types:
      - completed

jobs:
  build:
    uses: octopusden/octopus-base/.github/workflows/common-check-and-register-release.yml@v2.1.7
    if:  "${{ github.event.workflow_run.conclusion == 'success' }}"
    with:
      artifact-pattern: "octopus/octopus-parent/_VER_/octopus-parent-_VER_.pom"
    secrets: inherit
