name: Maven Release

on: workflow_dispatch

jobs:
  build:
    uses: octopusden/octopus-base/.github/workflows/common-java-maven-release.yml@7ea1efe169737531e2508ac6620fa7b534e5c8fc
    with:
      java-version: '11'
    secrets: inherit
